Flask.ext.rbac.RBAC
--------------

.. autoclass:: flask_prbac.__init__.RBAC
   :members:
   :inherited-members:


Flask.ext.rbac.model.RoleMixin
------------------------------

.. autoclass:: flask_prbac.model.RoleMixin
   :members:
   :inherited-members:


Flask.ext.rbac.model.UserMixin
------------------------------

.. autoclass:: flask_prbac.model.UserMixin
   :members:
   :inherited-members:
